// Code generated by protoc-gen-go. DO NOT EDIT.
// source: minuet_customer.proto

/*
Package minuet_customer is a generated protocol buffer package.

It is generated from these files:
	minuet_customer.proto

It has these top-level messages:
	Request
	Response
*/
package minuet_customer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Response struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "minuet_customer.Request")
	proto.RegisterType((*Response)(nil), "minuet_customer.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MinuetCustomer service

type MinuetCustomerClient interface {
	Read(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type minuetCustomerClient struct {
	cc *grpc.ClientConn
}

func NewMinuetCustomerClient(cc *grpc.ClientConn) MinuetCustomerClient {
	return &minuetCustomerClient{cc}
}

func (c *minuetCustomerClient) Read(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/minuet_customer.MinuetCustomer/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MinuetCustomer service

type MinuetCustomerServer interface {
	Read(context.Context, *Request) (*Response, error)
}

func RegisterMinuetCustomerServer(s *grpc.Server, srv MinuetCustomerServer) {
	s.RegisterService(&_MinuetCustomer_serviceDesc, srv)
}

func _MinuetCustomer_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinuetCustomerServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/minuet_customer.MinuetCustomer/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinuetCustomerServer).Read(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _MinuetCustomer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "minuet_customer.MinuetCustomer",
	HandlerType: (*MinuetCustomerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _MinuetCustomer_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "minuet_customer.proto",
}

func init() { proto.RegisterFile("minuet_customer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0xcd, 0xcc, 0x2b,
	0x4d, 0x2d, 0x89, 0x4f, 0x2e, 0x2d, 0x2e, 0xc9, 0xcf, 0x4d, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x47, 0x13, 0x56, 0x92, 0xe4, 0x62, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e,
	0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c,
	0x51, 0x92, 0xe2, 0xe2, 0x08, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x45, 0x97, 0x33, 0xf2,
	0xe7, 0xe2, 0xf3, 0x05, 0x9b, 0xe4, 0x0c, 0x35, 0x48, 0xc8, 0x96, 0x8b, 0x25, 0x28, 0x35, 0x31,
	0x45, 0x48, 0x42, 0x0f, 0xdd, 0x66, 0xa8, 0xf9, 0x52, 0x92, 0x58, 0x64, 0x20, 0xc6, 0x2b, 0x31,
	0x38, 0x29, 0x47, 0x29, 0xa6, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x67,
	0x94, 0x56, 0x66, 0x94, 0x15, 0xea, 0xa3, 0xa9, 0x4f, 0x62, 0x03, 0x7b, 0xc2, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0xd2, 0xec, 0xf2, 0x32, 0xdd, 0x00, 0x00, 0x00,
}
